name: Tp1 - markov

on:
  pull_request:
    branches: [main, master]

jobs:

  # 1. Install & Cache Dependencies 
  install:
    uses: ./.github/workflows/npm_install.yaml


  # 2. Lint 
  lint:
    needs: install
    uses: ./.github/workflows/npm_lint.yaml
    with:
      cache_key: ${{ needs.install.outputs.cache_key }}
      cache_path: ${{ needs.install.outputs.cache_path }}

  # 2. Run tests ( unit , integration , e2e )
  test:
    needs: install
    uses: ./.github/workflows/npm_test.yaml
    with:
      cache_key: ${{ needs.install.outputs.cache_key }}
      cache_path: ${{ needs.install.outputs.cache_path }}

  # 3. Comment the Pr about test execution 
  comment_test_execution:
    needs: test
    if: always()
    permissions:
      pull-requests: write
    uses: ./.github/workflows/test_report_comment_pr.yaml
    with:
      test_result: ${{ needs.test.result }}

  # 3. Publish test report to github pages 
  publish_test_report:
    needs: test
    if: always()
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/test_report_publish_github_page.yaml
    with:
      artifact_name: ${{ needs.test.outputs.artifact_name }}
