name: npm_test

on:
  workflow_call:
    inputs:
        cache_key:
          required: true
          type: string
        cache_path:
          required: true
          type: string
    outputs:
      artifact_name:
        value: allure-results # matches the name of the artifact below 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v5
        with:
          path: ${{ inputs.cache_path }}
          key: ${{ inputs.cache_key }}
  

      - name: Unit Test
        run: npm test

      - name: Generate test report
        if: always()
        run: npx allure generate allure-results -o allure-results --clean

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-results
          path: allure-results
