name: npm_test

on:
  workflow_call:
    inputs:
        cache_key:
          type: string
        cache_path:
          type: string
    outputs:
      artifact_name:
        value: allure-report # matches the name of the artifact below 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Clone repository 
      - uses: actions/checkout@v6

      # Setup Node using specific version 
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      # Load dependencies 

      # If cache deps is specified : use it 
      - uses: actions/cache@v5
        if: ${{ inputs.cache_key != ''  && inputs.cache_path != '' }} 
        with:
          path: ${{ inputs.cache_path }}
          key: ${{ inputs.cache_key }}
      
      # Else : install deps 
      - if: ${{ inputs.cache_key == ''  && inputs.cache_path == '' }} 
        run: npm ci 
  
      # Run tests 
      - name: Run Test ( unit, integration , e2e )
        run: npm test


      # Generate the test report 
      - name: Generate test report
        if: always()
        run: |
          npx allure generate allure-results --clean

      # Save the report as artifact 
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-report
          path: allure-report
