name: test_result_publish_github_page

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # Download the test report 
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: allure-report

      # Setup pages 
      - uses: actions/configure-pages@v5

      # Upload the test report to github pages 
      - uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report/
      
      # Deploy it to serve it as static file 
      - id: deployment
        uses: actions/deploy-pages@v4
        
      # Echo the url in order to retrieve the artifact
      - run: echo ${{ steps.deployment.outputs.page_url }}
