name: test_result_publish_github_page

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: allure-results

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v4
        with:
          path: allure-results/

      - id: deployment
        uses: actions/deploy-pages@v4

      - run: echo ${{ steps.deployment.outputs.page_url }}
